### ISSUE TITLE
Invalid Request when submitting

### ISSUE THREAD

**Issue by ScottieR** [doorkeeper-gem/doorkeeper-grants_assertion#10]
Hi there, really excited to use your gem, however I'm running into a problem (which may well be user error).

When I submit the following request, I get an "invalid request error" from doorkeeper (I've truncated the client_id, which is a valid application_id set up through Doorkeeper at oauth/applications, and the assertion param, which contains a valid oauth token from facebook):

curl -X POST --data "client_id=609336...dc431&assertion=CA...ROpHGFK&assertion_type=facebook" http://localhost:3000/oauth/token

This is how I have set up my doorkeeper initializer:

Doorkeeper.configure do
resource_owner_from_assertion do
    if params[:assertion_type] == "facebook"
      facebook = URI.parse('https://graph.facebook.com/me?access_token=' +
      params[:assertion])
      response = Net::HTTP.get_response(facebook)
      user_data = JSON.parse(response.body)
      User.find_by(provider: "facebook", uid: user_data['id'])
    end
  end

  grant_flows %w(assertion password client_credentials authorization_code implicit)
end

This returns the error: 

{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an unsupported parameter value, or is otherwise malformed."}

Am I submitting the parameters incorrectly or missing something?  Thanks for your help.

**Comment by ScottieR** [comment]
Well, of course, right after submitting I figured it out.  I had to add "grant_type=assertion" to the request, and since I'm using a custom tokens controller to add headers, I had to add the resource_owner_from_assertion method into it.

Left this up in case someone else is unsure what params to submit, since I had to poke around in the spec tests to figure it out.

**Comment by tute** [comment]
Thanks! Will close as it's not a bug, still google-able. If you think it's worth it to start a wiki with this kind of knowledge, or the README, contributions are most welcome. Thanks again!
