### ISSUE TITLE
Scrub assertion parameter in the request

### ISSUE THREAD

**Issue by baxang** [doorkeeper-gem/doorkeeper-grants_assertion#29]
Hi,

I've noticed the plain `assertion` parameter's value is shown in my logs as well as in Rollbar reports. I think the assertion strings should be treated as secure as [Doorkeeper does for authorization codes, tokens](https://github.com/doorkeeper-gem/doorkeeper/blob/ad833b7d0c572b6e34956b4926f5d2feef802252/lib/doorkeeper/engine.rb#L3-L5).

Maybe we can add a new `initializer` block in `railtie.rb` to add `assertion` to `app.config.filter_parameters` in the same fashion?

**Comment by matfiz** [comment]
Thank you!

**Comment by baxang** [comment]
Thanks @matfiz By any change do you have a new release planned?

**Comment by matfiz** [comment]
Yes, once the work on https://github.com/doorkeeper-gem/doorkeeper-grants_assertion/pull/28 is done, I will release a new version
