### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by christopherhein** [doorkeeper-gem/doorkeeper-grants_assertion#7]
Hey @tute,

What do you need from someone in terms of maintaining this? I see there is one open PR I'd be interesting in trying to help out if I can…

**Comment by tute** [comment]
I need someone to move it forward. I'm willing to help if you get stuck, but pretty much everything! Make it work, test it, garden issue tracker, merge/reject PRs, etc.

Gave you access to do all of this in this repo, let's see what can we do! Thanks.

**Comment by keaplogik** [comment]
Looking for an up to date release of this gem. Can we get a bump in the version and a latest in rubygems.org?

**Comment by tute** [comment]
That would not be a "release", as it's not tested or even human-tested to make sure it works. Until that happens, please use `github: doorkeeper-gem/doorkeeper-grants_assertion` in your `Gemfile`. If you need to merge in updates I'll be responsive to your PRs. Thanks!

**Comment by matfiz** [comment]
@christopherhein @tute At the company I work we are currently quite heavily using this gem. We handle google, FB and magic link login through grants assertion. I am willing to maintain this gem :) Then the docs can be extended (and updated basing on API changes) to support FB and Google login flow and we can keep the updates to meet the changes in doorkeeper gem.

Currently in doorkeeper 3.1 breaks the compatibility of this gem (because of the way authorization request was modified). See https://github.com/doorkeeper-gem/doorkeeper-grants_assertion/pull/17

**Comment by tute** [comment]
Thanks, @matfiz! Would you like contributor access to this repo?

**Comment by diegoy** [comment]
It would be great if we could release a version that is compatible with doorkeeper 3.1

Now that #18 has been fixed I'm using it in production and it looks like it's working.

**Comment by matfiz** [comment]
@tute it would be great!
@diegoy i can handle that and maintain updates, if @tute agrees.

**Comment by diegoy** [comment]
@matfiz If you need a pair of hands for something I'm glad to help :)

**Comment by tute** [comment]
@matfiz added. Letting know the other developer, @NuckChorris, know.

**Comment by onshi** [comment]
@diegoy currently we are using version from #18 with doorkeeper 3.1.0 on our staging, so far, so good

**Comment by NuckChorris** [comment]
Glad to have any help, obviously a release can't be made until the proper Doorkeeper hooks are in place, but right now we can probably build against that fork and maybe some infrastructural cleanup

**Comment by tute** [comment]
@matfiz I added 2FA requirement for members of this org. That kicked you out of it, when you enable it I'll be able to invite you back.

**Comment by matfiz** [comment]
@tute 2FA enabled, I should have done it long time ago!

**Comment by tute** [comment]
> @tute 2FA enabled, I should have done it long time ago!

Invitation sent! Reminder just in case: enable 2FA for your GitHub email account as well. :)

**Comment by matfiz** [comment]
@tute thanks! Yeah, I keep 2FA-enabled, Github was sadly the last (as I use self-hosted Gitlab on a daily basis).

**Comment by pedrocarmona** [comment]
@matfiz can you release in ruby gems?

**Comment by matfiz** [comment]
sure, will do :)

**Comment by pedrocarmona** [comment]
@tute can you release in rubygems or update maintainers in rubygems?  
https://rubygems.org/gems/doorkeeper-grants_assertion/versions/0.0.1

**Comment by matfiz** [comment]
@pedrocarmona I've emailed @tute, I'm waiting to be added to rubygems maintainers :)

**Comment by pedrocarmona** [comment]
Thanks for update @matfiz

**Comment by tute** [comment]
> @pedrocarmona I've emailed @tute, I'm waiting to be added to rubygems maintainers :)

Added! Thank you. Closing this issue for now, thanks to @matfiz.

**Comment by matfiz** [comment]
Thanks, @tute!

@pedrocarmona Version 0.1.0 released to Rubygems 🎆

**Comment by pedrocarmona** [comment]
👍
